### PR TITLE
Milestone 1: Newsweek

### PR DESCRIPTION
**Pull request by george-swift**
## Requirements
This project consists of replicating [this website](https://web.archive.org/web/20210120125445/https://www.newsweek.com/) using Bootstrap. 
For this milestone, we are building the header and footer using bootstrap responsive grid classes.

### CODE REVIEW

**Review by blackpintz — APPROVED** [review]
# Status: Approved 🎉

## Hello team 👋,

**Great job on this milestone 👏.**

## Highlights.

- **You have installed Bootstrap properly.**
- **You linter checks work properly.**
- **You are using more of bootstrap classes and less of custom classes.**

## Improvements to note moving forward ▶️ 

- **Ensure your webpage is responsive. Example, the menu at the bottom of the red navbar hides and a hamburger button is seen for medium and small screen sizes.**
- **Ensure the spacing and positioning of elements match that of the original page for all screen sizes. Example in the Navbar section, the Navbar logo should be centred for desktop screen size and aligned to the left for medium and small screen-sizes.**
- **Remember to add the input field at the bottom of the red navbar as it is shown in the original page.**

## Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

**Review by blackpintz — CHANGES_REQUESTED** [review]
# Status: Changes Required 🛑

## Hello team 👋,

**Great job on this milestone 👏.**

## Highlights

- **You webpage is responsive.**
- **Your webpage looks like the original.**

## Improvements to note moving forward ▶️

- **Update your Readme file with information about your project instead of info from the Microverse template. Example use the correct links for your socials and project demo.**
- **Add the following sections in column three: Opinion 🔹 Sponsored Insights/ Rankings 🔹 Free signup.**
- **Most of the sections in the columns are not displayed on the mobile screen size. You only display the Featured stories, The Debate, Top Story and Sponsored Insight/Rankings. Please add the other sections.**
- **All images should be links.**
- **All titles in the Latest News and More Stories sections should be links as well.**

## Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

**Comment by kuawi** [comment]
Hi there!

Today we worked on milestone 3 and successfully completed it.
About the requested changes, we wanted to let you know we worked on them but couldn't complete them all today, we are planning to finish those tomorrow along side any other newly requested changes. 

More specifically here is a list of the changes we've addressed so far:

- Improve responsiveness on top bar: The newsweeek logo size and position works properly now, the burger menu is now present in smaller viewports.
- README updated.
- Images are now links.

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey team, 👋

You have done an amazing job implementing the requirements for this project.

However, there are still some changes 👇 you need to implement to approve this request 🔍

### Changes Required ♻️ 

- [x] You're missing the `Opinions` and `Free Sign Up` sections. On desktop screen size, they are located in the 3rd column to the right.
- [ ] You're missing a form with a search input in the main navigation menu right below the Navbar.

#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime** or
 <a href="mailto:phillipmusiime@gmail.com"> gmail</a> &nbsp; &nbsp; [Twitter Follow](https://twitter.com/intent/follow?screen_name=Phillip_Ug) &nbsp; &nbsp; [GitHub followers](https://github.com/PhillipUg)

**Review by uryelah — APPROVED** [review]
Hi **George Itok & Jose Lozano Salcedo**, I'm Sarah your reviewer for this PR 👩‍🚀 

You did a great job updating your project according to the last TSE requests, good job paying attention to the website colors and handling the images well!

Good luck with your HTML&CSS Capstones! 🚀  

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**

---------

### Optional changes

- [ ] [OPTIONAL] The original NewsWeek page has some hover effects for the article titles, why don't you try your hand at those, hover effects are very useful in improving the general feel of a webapp and it's UX.

---------

    
    
**Keep being awesome devs and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
